name: release

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: yarn

      - name: Tests
        run: yarn test:ci

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        env:
          github-token: ${{ secrets.COVERALLS_TOKEN }}

  release:
    name: Release

    needs: tests

    if: "!contains(github.event.head_commit.message, 'chore(release)')"

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
            node-version: '18.x'
            registry-url: 'https://registry.npmjs.org'
            scope: '@zerfo'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Copy release files
        run: yarn copy-release-files

      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
