name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"

    runs-on: ubuntu-latest

    steps:
      - name: Initialize Git user
        run: |
          git config --global user.name 'Zerfo'
          git config --global user.email 'nikolay.smekalin@gmail.com'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.NPM_PUBLISH_KEY }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Tests
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Copy release files
        run: npm run copy-release-files

      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        env:
          github-token: ${{ secrets.COVERALLS_TOKEN }}